# Generated by Django 4.0.5 on 2022-06-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_devolucion',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
