# Generated by Django 4.0.5 on 2022-06-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamo', '0002_remove_prestamo_fecha_devolucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
