# Generated by Django 4.0.5 on 2022-06-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamo', '0003_alter_prestamo_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='estado',
            new_name='entregado',
        ),
    ]
