# Generated by Django 4.0.5 on 2022-06-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prestamo', '0004_rename_estado_prestamo_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='entregado',
        ),
    ]
